### ISSUE TITLE
Question about backward propagation

### ISSUE THREAD

**Issue by chendiqian** [UCLA-StarAI/SIMPLE#1]
Dear contributors,

For the `marginals` function in the file `DVAE/DVAE-SIMPLE.ipynb`, why do you calculate a grad of `log_pr` over `log_p`? I think grad of `log_pr` over `theta` makes more sense to me.

**Comment by KareemYousrii** [comment]
Hi Chendi,

I believe the calculation is correct as it stands. It is a well known fact that the derivatives of the log partition function w.r.t the log unnormalized probabilities yields the log conditional probabilities. To see that, consider that taking the gradient of the log partition function first gives you the partition function p(alpha) in the denominator. Now you need to differentiate what's within the log, which yields the exp log-probs of the models depending on the variable w.r.t which we're differentiating; this yields p(Xi ^ alpha) in the numerator. p(Xi ^ alpha)/p(alpha) is exactly the conditional marginals.

For a more formal proof, you can check Theorem 1 in the paper.

**Comment by h-spiess** [comment]
Hey. I was actually similarly confused. I think this is due to some incorrect/sloppy notation in the paper. In the pseudocode of the backward-pass in the paper, mu is said to be the gradient of the log partition function w.r.t. to theta (and not w.r.t. to the logprob). However, if one would change that, then I guess the JVP in the next step is underspecified (would miss the fact that the thetas are passed through a sigmoid into the marginal computation). Am I missing something?

Nevertheless, very nice work. I was able to reimplement your code and about to apply it to my problem.

Thanks, Heiner
